#!/bin/bash
. /var/openpanel/api/sh/module.sh

fatal() {
	echo "$1"
	exit 1
}

A2CONFDIR=/etc/apache2/sites-enabled

Vhost.delete() {
	SERVERNAME=$(coreval Vhost id)
	HOSTDIR=/var/www/${SERVERNAME}

	authd deletefile ${A2CONFDIR}/${SERVERNAME}.conf
	[ -r ${A2CONFDIR}/${SERVERNAME}-ssl.conf ] && HTTPS.delete
	authd deletedir ${HOSTDIR}
}

Vhost.create() {
	SERVERNAME=$(coreval Vhost id)
	WEBMASTER=$(coreval Vhost admin)
	HOSTDIR=/var/www/${SERVERNAME}

cat <<EOB > $(pwd)/${SERVERNAME}.conf
<VirtualHost *:80>
	ServerAdmin ${WEBMASTER}
	Servername ${SERVERNAME}

	DocumentRoot ${HOSTDIR}/public
</VirtualHost>
EOB

	authd makedir ${HOSTDIR}
	authd makedir ${HOSTDIR}/tmp
	authd makedir ${HOSTDIR}/log
	authd makedir ${HOSTDIR}/public

	authd installfile ${SERVERNAME}.conf ${A2CONFDIR}/
}

HTTPS.delete() {
	SERVERNAME=$(coreval Vhost id)
	HOSTDIR=/var/www/${SERVERNAME}

	authd deletefile ${A2CONFDIR}/${SERVERNAME}-ssl.conf
	authd deletedir ${HOSTDIR}/ssl
}

HTTPS.create() {
	SSLCERT=$(coreval HTTPS pem)
	SSLIP=$(coreval HTTPS ip)
	SERVERNAME=$(coreval Vhost id)
	WEBMASTER=$(coreval Vhost admin)
	HOSTDIR=/var/www/${SERVERNAME}

[ -z ${SSLIP} ] && SSLIP="*"

echo ${SSLCERT} | grep -q -- '-----BEGIN CERTIFICATE-----' || fatal "PEM doesn't contain a certificate"
echo ${SSLCERT} | grep -q -- '-----BEGIN RSA PRIVATE KEY-----' || fatal "PEM doesn't contain a private key"

cat <<EOB > $(pwd)/cert.pem
${SSLCERT}
EOB

cat <<EOB > $(pwd)/${SERVERNAME}-ssl.conf
<VirtualHost ${SSLIP}:443>
	ServerAdmin ${WEBMASTER}
	Servername ${SERVERNAME}

	DocumentRoot ${HOSTDIR}/public

	SSLEngine on
	SSLProtocol -all +TLSv1 +SSLv3
	SSLCertificateFile ${HOSTDIR}/ssl/cert.pem
</VirtualHost>
EOB

	authd makedir ${HOSTDIR}/ssl

	authd installfile cert.pem ${HOSTDIR}/ssl/
	authd installfile ${SERVERNAME}-ssl.conf ${A2CONFDIR}/
}

Vhost.update() {
	Vhost.create
}

implement OpenAppApache2.module
