#!/bin/bash
. /var/openpanel/api/sh/module.sh

fatal() {
	echo "$1"
	exit 1
}

A2CONFDIR=/etc/apache2/sites-enabled

restart_apache2() {

cat <<EOB > $(pwd)/ssl-namevirtualhost.conf
NameVirtualHost *:443
EOB

	[ ! -f /etc/apache2/conf.d/ssl-namevirtualhost.conf ] && authd installfile ssl-namevirtualhost.conf /etc/apache2/conf.d

	authd reloadservice apache2
}

Vhost.delete() {
	SERVERNAME=$(coreval Vhost id)
	HOSTDIR=/var/www/${SERVERNAME}

	authd deletefile ${A2CONFDIR}/${SERVERNAME}.conf
	[ -r ${A2CONFDIR}/${SERVERNAME}-ssl.conf ] && HTTPS.delete
	authd deletedir ${HOSTDIR}

	restart_apache2
}

Vhost.create() {
	SERVERNAME=$(coreval Vhost id)
	WEBMASTER=$(coreval Vhost admin)
	HOSTDIR=/var/www/${SERVERNAME}

[ -z ${WEBMASTER} ] && WEBMASTER=webmaster@unknown

cat <<EOB > $(pwd)/${SERVERNAME}.conf
<VirtualHost *:80>
	ServerAdmin ${WEBMASTER}
	Servername ${SERVERNAME}

	DocumentRoot ${HOSTDIR}/public

    CustomLog /var/log/apache2/${SERVERNAME}.access.log combined
    ErrorLog  /var/log/apache2/${SERVERNAME}.error.log
</VirtualHost>
EOB

	authd makedir ${HOSTDIR}
	authd makedir ${HOSTDIR}/tmp
	authd makedir ${HOSTDIR}/log
	authd makedir ${HOSTDIR}/public

	authd installfile ${SERVERNAME}.conf ${A2CONFDIR}

	restart_apache2
}

HTTPS.delete() {
	SERVERNAME=$(coreval Vhost id)
	HOSTDIR=/var/www/${SERVERNAME}

	authd deletefile ${A2CONFDIR}/${SERVERNAME}-ssl.conf
	authd deletedir ${HOSTDIR}/ssl

	restart_apache2
}

HTTPS.create() {
	SSLCERT=$(coreval HTTPS pem)
	SSLIP=$(coreval HTTPS ip)
	SERVERNAME=$(coreval Vhost id)
	WEBMASTER=$(coreval Vhost admin)
	HOSTDIR=/var/www/${SERVERNAME}

[ -z ${SSLIP} ] && SSLIP="*"

cat <<EOB > $(pwd)/cert.pem
${SSLCERT}
EOB

/var/openpanel/bin/validatepem.py $(pwd)/joomla.pem

[ $? -eq 0 ] || exiterror "Your certificate has issues. Is the private key included (and without a passphrase)?"

cat <<EOB > $(pwd)/${SERVERNAME}-ssl.conf
<VirtualHost ${SSLIP}:443>
	ServerAdmin ${WEBMASTER}
	Servername ${SERVERNAME}

	DocumentRoot ${HOSTDIR}/public

	SSLEngine on
	SSLProtocol -all +TLSv1 +SSLv3
	SSLCertificateFile ${HOSTDIR}/ssl/cert.pem
</VirtualHost>
EOB

	authd makedir ${HOSTDIR}/ssl

	authd installfile cert.pem ${HOSTDIR}/ssl
	authd installfile ${SERVERNAME}-ssl.conf ${A2CONFDIR}

	restart_apache2
}

Vhost.update() {
	Vhost.create
}

implement OpenAppApache2.module
