#!/bin/sh
# This file is part of OpenPanel - The Open Source Control Panel
# OpenPanel is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, using version 3 of the License.
#
# Please note that use of the OpenPanel trademark may be subject to additional 
# restrictions. For more information, please visit the Legal Information 
# section of the OpenPanel website on http://www.openpanel.com/

if [ -d /etc/httpd ]; then
  if [ ! -d /etc/httpd/openpanel.d ]; then
    echo "No /etc/httpd/openpanel.d"
    echo "quit" >&3
    exit 1
  fi
  if [ ! -f /etc/httpd/conf.d/openpanel.conf ]; then
    echo "File openpanel.conf not found in etc/httpd/conf.d"
    echo "quit" >&3
    exit 1
  fi
else
  if [ ! -d /etc/apache2 ]; then
    echo "Apache not found"
    echo "quit" >&3
    exit 1
  fi
  if [ ! -f /etc/apache2/conf.d/openpanel.conf ]; then
    echo "Openpanel.d not included in config"
    echo "quit" >&3
    exit 1
  fi
fi
